Repository sublimelsp/LSP, pull requests merged in 2018-12, with the labels that each got.

#473 Make workspace/applyEdit reply back to the language server
  plugin/core/edit.py
  plugin/core/test_rpc.py
  plugin/core/test_windows.py
  plugin/core/types.py
  plugin/core/windows.py
Labels: bug

#474 Allow user to trigger custom commands
  boot.py
  plugin/execute_command.py
Labels: enhancement

#489 Add a bulb
  LSP.sublime-settings
  docs/index.md
  icons/lightbulb.png
  icons/lightbulb@2x.png
  icons/lightbulb@3x.png
  plugin/code_actions.py
  plugin/core/helpers.py
  plugin/core/settings.py
  plugin/core/types.py
Labels: enhancement, investigation
